// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOjjq_BIp8XmJWw94NAGGNiXBS5KnlZ4',
    appId: '1:471950980952:web:f4c2ae9e26835d23d2572d',
    messagingSenderId: '471950980952',
    projectId: 'sabi-cde2b',
    authDomain: 'sabi-cde2b.firebaseapp.com',
    storageBucket: 'sabi-cde2b.firebasestorage.app',
    measurementId: 'G-2CD76QXJJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcEeyQ0zYV0QD9pyt5YDccV_dXBOy-4Tw',
    appId: '1:471950980952:android:51b9d820dda98145d2572d',
    messagingSenderId: '471950980952',
    projectId: 'sabi-cde2b',
    storageBucket: 'sabi-cde2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fdYnM9NLAtGTM9NNWsQQCzqojVU5Xks',
    appId: '1:471950980952:ios:3dbe06e6f5e44d2ad2572d',
    messagingSenderId: '471950980952',
    projectId: 'sabi-cde2b',
    storageBucket: 'sabi-cde2b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSabi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fdYnM9NLAtGTM9NNWsQQCzqojVU5Xks',
    appId: '1:471950980952:ios:3dbe06e6f5e44d2ad2572d',
    messagingSenderId: '471950980952',
    projectId: 'sabi-cde2b',
    storageBucket: 'sabi-cde2b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSabi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqOjjq_BIp8XmJWw94NAGGNiXBS5KnlZ4',
    appId: '1:471950980952:web:ad677c8edb40ceb3d2572d',
    messagingSenderId: '471950980952',
    projectId: 'sabi-cde2b',
    authDomain: 'sabi-cde2b.firebaseapp.com',
    storageBucket: 'sabi-cde2b.firebasestorage.app',
    measurementId: 'G-GSXSJMWT45',
  );
}
